<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Penilaian - {{ $project->nama_project }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #82C17D; padding-bottom: 10px; margin-bottom: 20px; }
        .logo { width: 80px; height: auto; }
        .title { font-size: 18px; font-weight: bold; margin-top: 5px; }
        .subtitle { font-size: 14px; color: #666; }
        .section-title { font-size: 14px; font-weight: bold; background-color: #f4f4f4; padding: 5px; border-left: 4px solid #82C17D; margin-top: 20px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f9f9f9; width: 30%; font-weight: bold; }
        .footer { position: fixed; bottom: -30px; left: 0; right: 0; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #ddd; padding-top: 5px; }
        .signature { margin-top: 50px; text-align: right; }
        .signature-name { font-weight: bold; text-decoration: underline; margin-top: 70px; }
    </style>
</head>
<body>

    <div class="header">
        <div class="title">KANTOR JASA PENILAI PUBLIK (KJPP)</div>
        <div class="subtitle">Laporan Hasil Penilaian Aset Properti</div>
    </div>

    <div class="section-title">1. Informasi Umum Project</div>
    <table>
        <tr>
            <th>Nama Project</th>
            <td>{{ $project->nama_project }}</td>
        </tr>
        <tr>
            <th>Tanggal Penilaian</th>
            <td>{{ \Carbon\Carbon::parse($project->tanggal_mulai ?? now())->translatedFormat('d F Y') }}</td>
        </tr>
        <tr>
            <th>Asal Instansi</th>
            <td>{{ $project->asal_instansi ?? '-' }}</td>
        </tr>
        <tr>
            <th>Status Laporan</th>
            <td style="color: green; font-weight:bold;">{{ strtoupper($project->status) }}</td>
        </tr>
    </table>

    <div class="section-title">2. Identitas Klien</div>
    <table>
        <tr>
            <th>Nama Klien</th>
            <td>{{ $client ? $client->name : '-' }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ $client ? $client->email : '-' }}</td>
        </tr>
    </table>

    <div class="section-title">3. Data Fisik Properti</div>
    @if($fisik)
        <table>
            <tr>
                <th>Luas Tanah (m2)</th>
                <td>{{ number_format($fisik->land_area, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <th>Luas Bangunan (m2)</th>
                <td>{{ number_format($fisik->building_area, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <th>Bentuk Tapak</th>
                <td>{{ $fisik->site_shape }}</td>
            </tr>
            <tr>
                <th>Topografi Kontur</th>
                <td>{{ $fisik->topography_contour }}</td>
            </tr>
        </table>
    @else
        <p>Data fisik belum tersedia atau belum disurvey.</p>
    @endif

    <div class="section-title">4. Kesimpulan Nilai Properti</div>
    @if($nilai)
        <table style="border: 2px solid #82C17D;">
            <tr>
                <th style="background-color: #e6f4e5;">Nilai Pasar</th>
                <td style="font-size: 16px; font-weight: bold; color: #2d6a4f;">Rp {{ number_format($nilai->nilai_pasar, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <th style="background-color: #e6f4e5;">Nilai Indikasi (Likuidasi)</th>
                <td style="font-size: 14px; font-weight: bold;">Rp {{ number_format($nilai->nilai_indikasi, 0, ',', '.') }}</td>
            </tr>
        </table>
        <p><em>*Nilai di atas merupakan hasil kalkulasi berdasarkan data yang dihimpun pada saat penilaian.</em></p>
    @else
        <p>Data penilaian/kalkulasi belum tersedia.</p>
    @endif

    <div class="signature">
        <p>Jakarta, {{ $tanggal_cetak }}</p>
        <p>Penilai Publik,</p>
        <div class="signature-name">{{ Auth::user()->name ?? 'Administrator' }}</div>
        <div>NIPP. -</div>
    </div>

    <div class="footer">
        Generated by Sistem Informasi KJPP &copy; {{ date('Y') }} - Laporan ini sah dan dicetak secara otomatis.
    </div>

</body>
</html>
